version: '2.29.2'

services:
  mysql_db:
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: netology
      MYSQL_USER: repin
      MYSQL_PASSWORD: 1
    volumes:
      - ./dbdata:/var/lib/mysql/